### ISSUE TITLE
Robot page redesign

### ISSUE THREAD

**Issue by GLDuval** [clubcapra/clubcapra.github.io#32]
The current layout of the Robot page is buggy. The page should be redesigned from stratch to add more detail and information about our robots.

Maybe include sections like:
- Mapping with a clear picture of a 3D map
- Manipulation with dummy rescue
- Our robots on different terrain
- etc...

**Comment by patates-cipsi418** [comment]
I like the concept of a nav bar with different versions of the product:
![image](https://github.com/clubcapra/clubcapra.github.io/assets/81366683/2a8c7ac4-8631-4ad7-9617-147d25a4c61b)
[link](https://www.kia.ca/fr/vehicles/2024/ev9/specs?trimCode=Wind+RWD)
We can implement this for the diffèrent robots.

**Comment by patates-cipsi418** [comment]
When reloading, the nav bar disaper.
