### ISSUE TITLE
Inconsistent content layout in some pages

### ISSUE THREAD

**Issue by GLDuval** [clubcapra/clubcapra.github.io#34]
Content should be padded equally. 
Issue can be seen on the Home and Competition pages.
![image](https://github.com/clubcapra/clubcapra.github.io/assets/46896242/ce09eed5-1755-4050-b57b-63cc2e789a08)
![image](https://github.com/clubcapra/clubcapra.github.io/assets/46896242/6bb14f23-08b3-43ef-b5cc-6c781cb4bb6f)

**Comment by patates-cipsi418** [comment]
Closing this issue because of site redesign
