### ISSUE TITLE
Fix Capra overlay not showing up on home page

### ISSUE THREAD

**Issue by GLDuval** [clubcapra/clubcapra.github.io#37]
When accessing the Home page from the nav bar, the Capra overlay is not displayed.
**Actual Result:**
![image](https://github.com/clubcapra/clubcapra.github.io/assets/46896242/bb260fd4-d29d-44aa-9ed3-c25a06911a7e)
**Expected Result:**
![image](https://github.com/clubcapra/clubcapra.github.io/assets/46896242/a2b7d1bf-bdf2-454e-b73c-15d2207ee71f)

**Comment by patates-cipsi418** [comment]
I will try to replace fullpage.js

**Comment by Leuchak** [comment]
try setting a z-index for the .vg-video CSS class.
