### ISSUE TITLE
[mobile] Sidebar transparancy bug

### ISSUE THREAD

**Issue by McCaroon** [clubcapra/clubcapra.github.io#40]
When opening the sidebar on mobile there seems to be a bug where the background is transparent and the actual page you're on is red. In the following picture, i'm on the page named "Capra" however I can't see that since theres a red background on it.
![image](https://github.com/clubcapra/clubcapra.github.io/assets/43826975/5abe9b0b-f265-4537-bf9e-053bc45a61f0)

**Comment by VignRaph** [comment]
@McCaroon can you test again if this was fixed indirectly by another PR, i don't get this bug on my phone so i can't test if it is fixed

**Comment by patates-cipsi418** [comment]
Closing this issue because of redesign
