### ISSUE TITLE
Refreshing page creates a download request

### ISSUE THREAD

**Issue by McCaroon** [clubcapra/clubcapra.github.io#43]
When i'm on any page other than the "capra" home page and I hit F5 to refresh the page, it prompts a download. The download in question seems to be the actual HTLM file of the page you're currently on.

**Comment by Leuchak** [comment]
with wich browser ?

**Comment by Leuchak** [comment]
mhh, the routes are managed on the client side with vue-router. However, the files don't actually exist. Only the index.html page exists. As a quick workaround, the index.html page is copied with the name of each route.
